[package]
name = "sandwork"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
serde = { version = "1", features = [ "derive" ] }
toml = { version = "0.9", default-features = false, features = [ "serde", "parse" ] }

[[bin]]
name = "sandwork"
path = "sandwork.rs"
